### PR TITLE
Change FF_PROFILE_UNKNOWN to AV_PROFILE_UNKNOWN in ffmpeg8

### LINKED ISSUE #38: Compile errors with FFmpeg 8.0
```
> mix deps.compile xav --force
==> xav
mkdir -p /Users/kevinschweikert/projects/app/_build/dev/lib/xav/priv
cc -O2 -g -march=native  -fPIC -shared -undefined dynamic_lookup -I/Users/kevinschweikert/.local/share/mise/installs/erlang/28.0.1/erts-16.0.1/include -Ic_s
rc/xav $(pkg-config --cflags-only-I libavcodec libswscale libavutil libavformat libavdevice libswresample) $(pkg-config --libs-only-L libavcodec libswscale 
libavutil libavformat libavdevice libswresample) c_src/xav/xav_decoder.c c_src/xav/decoder.c c_src/xav/video_converter.c c_src/xav/audio_converter.c c_src/x
av/utils.c c_src/xav/channel_layout.c -o /Users/kevinschweikert/projects/app/_build/dev/lib/xav/priv/libxavdecoder.so -lavcodec -lswscale -lavutil
 -lavformat -lavdevice -lswresample
mkdir -p /Users/kevinschweikert/projects/app/_build/dev/lib/xav/priv
cc -O2 -g -march=native  -fPIC -shared -undefined dynamic_lookup -I/Users/kevinschweikert/.local/share/mise/installs/erlang/28.0.1/erts-16.0.1/include -Ic_s
rc/xav $(pkg-config --cflags-only-I libavcodec libswscale libavutil libavformat libavdevice libswresample) $(pkg-config --libs-only-L libavcodec libswscale 
libavutil libavformat libavdevice libswresample) c_src/xav/xav_reader.c c_src/xav/reader.c c_src/xav/video_converter.c c_src/xav/audio_converter.c c_src/xav
/utils.c -o /Users/kevinschweikert/projects/app/_build/dev/lib/xav/priv/libxavreader.so -lavcodec -lswscale -lavutil -lavformat -lavdevice -lswres
ample
mkdir -p /Users/kevinschweikert/projects/app/_build/dev/lib/xav/priv
cc -O2 -g -march=native  -fPIC -shared -undefined dynamic_lookup -I/Users/kevinschweikert/.local/share/mise/installs/erlang/28.0.1/erts-16.0.1/include -Ic_s
rc/xav $(pkg-config --cflags-only-I libavcodec libswscale libavutil libavformat libavdevice libswresample) $(pkg-config --libs-only-L libavcodec libswscale 
libavutil libavformat libavdevice libswresample) c_src/xav/xav_video_converter.c c_src/xav/video_converter.c c_src/xav/utils.c -o /Users/kevinschweikert/pro
jects/app/_build/dev/lib/xav/priv/libxavvideoconverter.so -lavcodec -lswscale -lavutil -lavformat -lavdevice -lswresample
mkdir -p /Users/kevinschweikert/projects/app/_build/dev/lib/xav/priv
cc -O2 -g -march=native  -fPIC -shared -undefined dynamic_lookup -I/Users/kevinschweikert/.local/share/mise/installs/erlang/28.0.1/erts-16.0.1/include -Ic_s
rc/xav $(pkg-config --cflags-only-I libavcodec libswscale libavutil libavformat libavdevice libswresample) $(pkg-config --libs-only-L libavcodec libswscale 
libavutil libavformat libavdevice libswresample) c_src/xav/xav_encoder.c c_src/xav/encoder.c c_src/xav/utils.c c_src/xav/channel_layout.c -o /Users/kevinsch
weikert/projects/app/_build/dev/lib/xav/priv/libxavencoder.so -lavcodec -lswscale -lavutil -lavformat -lavdevice -lswresample
c_src/xav/xav_encoder.c:21:28: error: use of undeclared identifier 'FF_PROFILE_UNKNOWN'
   21 |   encoder_config.profile = FF_PROFILE_UNKNOWN;
      |                            ^
c_src/xav/xav_encoder.c:116:35: error: use of undeclared identifier 'FF_PROFILE_UNKNOWN'
  116 |     if (encoder_config.profile == FF_PROFILE_UNKNOWN) {
      |                                   ^
c_src/xav/xav_encoder.c:306:12: error: use of undeclared identifier 'FF_PROFILE_UNKNOWN'
  306 |     return FF_PROFILE_UNKNOWN;
      |            ^
c_src/xav/xav_encoder.c:309:30: error: use of undeclared identifier 'FF_PROFILE_UNKNOWN'
  309 |   while (profile->profile != FF_PROFILE_UNKNOWN) {
      |                              ^
c_src/xav/xav_encoder.c:330:30: error: use of undeclared identifier 'FF_PROFILE_UNKNOWN'
  330 |   while (profile->profile != FF_PROFILE_UNKNOWN) {
      |                              ^
c_src/xav/xav_encoder.c:347:53: warning: 'sample_fmts' is deprecated [-Wdeprecated-declarations]
  347 |   const enum AVSampleFormat *sample_format = codec->sample_fmts;
      |                                                     ^
/opt/homebrew/Cellar/ffmpeg/8.0/include/libavcodec/codec.h:203:5: note: 'sample_fmts' has been explicitly marked deprecated here
  203 |     attribute_deprecated
      |     ^
/opt/homebrew/Cellar/ffmpeg/8.0/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
  100 | #    define attribute_deprecated __attribute__((deprecated))
      |                                                 ^
c_src/xav/xav_encoder.c:361:51: warning: 'supported_samplerates' is deprecated [-Wdeprecated-declarations]
  361 |   if (codec->type != AVMEDIA_TYPE_AUDIO || codec->supported_samplerates == NULL) {
      |                                                   ^
/opt/homebrew/Cellar/ffmpeg/8.0/include/libavcodec/codec.h:201:5: note: 'supported_samplerates' has been explicitly marked deprecated here
  201 |     attribute_deprecated
      |     ^
/opt/homebrew/Cellar/ffmpeg/8.0/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
  100 | #    define attribute_deprecated __attribute__((deprecated))
      |                                                 ^
c_src/xav/xav_encoder.c:365:35: warning: 'supported_samplerates' is deprecated [-Wdeprecated-declarations]
  365 |   const int *sample_rate = codec->supported_samplerates;
      |                                   ^
/opt/homebrew/Cellar/ffmpeg/8.0/include/libavcodec/codec.h:201:5: note: 'supported_samplerates' has been explicitly marked deprecated here
  201 |     attribute_deprecated
      |     ^
/opt/homebrew/Cellar/ffmpeg/8.0/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
  100 | #    define attribute_deprecated __attribute__((deprecated))
      |                                                 ^
3 warnings and 5 errors generated.
c_src/xav/encoder.c:45:26: error: use of undeclared identifier 'FF_PROFILE_UNKNOWN'
   45 |   if (config->profile != FF_PROFILE_UNKNOWN) {
      |                          ^
1 error generated.
make: *** [/Users/kevinschweikert/projects/app/_build/dev/lib/xav/priv/libxavencoder.so] Error 1
```

### PR DESCRIPTION
**Pull request by kevinschweikert**
Closes #38 

I don't know if this is the cleanest way to do it in C. I had an LLM help me

### CODE REVIEW

File: c_src/xav/decoder.h [hunk 1]
```diff
@@ -7,6 +7,14 @@
 
 #define MAX_FLUSH_BUFFER 16
 
+/* FFmpeg ≤ 7 used FF_PROFILE_UNKNOWN, FFmpeg ≥ 8 uses AV_PROFILE_UNKNOWN. */
+#if defined(AV_PROFILE_UNKNOWN)
```
Comment (gBillal) [inline c_src/xav/decoder.h]: Instead of duplicating this code in two files, put it in `utils.h` file. Also you can simplify it to
```c
#ifndef AV_PROFILE_UNKNOWN
#define AV_PROFILE_UNKNOWN FF_PROFILE_UNKNOWN
#endif
```

Comment (kevinschweikert) [reply c_src/xav/decoder.h]: ah perfect! Thanks!
